routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\StudentController;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', [StudentController::class, 'index']);

Route::resource('students', 'App\Http\Controllers\StudentController' );

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/students.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class students extends Model
{
    use HasFactory;

    //Table Name
    protected $table = "students";

    //Primary key
    public $primaryKey = 'id';

    // Timestamps
    public $timestamps = true;

    protected $fillable = ['firstName','lastName', 'phone_no', 'email', 'gender'];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('student.index');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\students;
use Illuminate\Http\Request;

class StudentController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = students::orderBy('created_at','desc')->paginate(5);
        return view('student.index')->with('students', $students);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {

        $this->validate($request,[
            'firstName'=> 'required',
            'lastName'=> 'required',
            'phone_no'=> 'required',
            'email'=> 'required',
        ]);

        students::create($request->all());
        return redirect('/')->with('success', 'Added '.$request->input('firstName') );

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(students $student)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(students $student)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $student)
    {
        //

        students::find($student)->update($request->all());
        return redirect('/')->with('success', 'Updated ' .$request->get('firstName'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy($student)
    {
        $rec = students::find($student);
        $name = $rec->firstName;
        $rec->delete();
        return redirect('/')->with('success', 'Deleted '.$name);
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    You are logged in! {{ Auth::user()->name }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/inc/messages.blade.php
@if(count($errors) > 0)
    @foreach($errors as $error)
        <div class="alert alert-danger">
            {{ $error }}
        </div>
    @endforeach
@endif


<!-- success modal  -->
@if( session('success'))
    <div  id="confirm" class="modal fade">
        <div class="modal-dialog modal-confirm">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="icon-box">
                        <i class="material-icons">check</i>
                    </div>
                </div>
                <div class="modal-body">
                    <p class="text-center"> {{ Auth::user()->name  }} You have succesfully <strong class="text-secondary">{{ session('success') }}</strong></p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-success btn-block" data-dismiss="modal">OK</button>
                </div>
            </div>
        </div>
    </div>
@endif


@if(session('error'))
    <!-- failed modal  -->
    <div id="failed" class="modal fade">
        <div class="modal-dialog modal-confirm">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="icon-box" style="background:darkred;">
                        <i class="material-icons" style="color:tomato;">close</i>
                    </div>
                </div>
                <div class="modal-body">
                    <p class="text-center"><strong class="text-secondary"> {{ session('error') }} </strong></p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary btn-block" style="background:darkred;" data-dismiss="modal">OK</button>
                </div>
            </div>
        </div>
    </div>

@endif

resources/views/inc/navbar.blade.php
<nav class="navbar navbar-expand-lg  bg-dark">
    <a class="navbar-brand" href="{{ url('/') }}"><strong class='text-warning'>SEMREM</strong><small class='text-default'>college</small></a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        {{-- left side of navbar --}}
        <ul class="navbar-nav mr-auto">

        </ul>
        <!-- Right Side Of Navbar -->
        <ul class="navbar-nav ml-auto">
            <!-- Authentication Links -->
            @guest
                @if (Route::has('login'))
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}"> Login </a>
                    </li>
                @endif
                @if (Route::has('register'))
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}"> Register </a>
                    </li>
                @endif
            @else

                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->name }}
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="dropdown-item">
                            @csrf
                            <a><button type="submit" class="btn btn-block"><strong class="text-danger"> Logout </strong></a>
                        </form>
                    </div>
                </li>
            @endguest
        </ul>
    </div>
</nav>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round|Open+Sans">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <title>{{ config('app.name', 'Welcome') }}</title>
    <link rel="shortcut icon" href="{{ asset('img/favicon.ico') }}"/>

    @yield('css')
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>
<body>
     <body style="background-color:grey;background-image: url('img/regBg.jpg')">
        @include('inc.navbar')
        <div class="container-fluid" ><br>
            @include('inc.messages')
            @yield('content')
        </div>
        @yield('modal')
    </body>
</body>
</html>

resources/views/student/index.blade.php
@extends('layouts.app')
@section('css')
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
@endsection
@section('content')
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-8"><h2>Student <b>Details</b></h2></div>
                    <div class="col-sm-4">
                        <button type="button" class="btn btn-info addNew" data-toggle="modal" data-target="#addNew"><i class="fa fa-plus"></i> Add New</button>

                    </div>
                </div>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>S/N </th>
                        <th >First Name</th>
                        <th >Last Name</th>
                        <th >Phone No.</th>
                        <th >Email </th>
                        <th >Gender </th>
                        <th >Actions </th>
                    </tr>
                </thead>
                <tbody>
                    @if (count($students) > 0)
                        @php $number = 1; @endphp
                        @foreach($students as $student)
                            <tr>
                                <td> {{ $number }} </td>
                                <td >{{ $student->firstName }}</td>
                                <td>{{ $student->lastName }}</td>
                                <td>{{ $student->phone_no }} </td>
                                <td>{{ $student->email }}</td>
                                <td>{{ $student->gender }}</td>
                                <td>
                                    <a  data-toggle="modal" data-target="#editRecord-{{ $number }}"><i class="material-icons edit" style="color: green;">edit </i> </a>
                                    <a  data-toggle="modal" data-target="#deleteRecord-{{ $number }}"><i class="material-icons" style="color: red;">delete </i> </a>

                                    <!-- edit Modal HTML -->
                                    <div class="modal fade" id="editRecord-{{ $number }}">
                                        <div class="modal-dialog modal-sm" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Edit {{ $student->firstName }} Details</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <form action="students/{{$student->id}}" method='POST'>
                                                    @csrf
                                                    @method('PUT')
                                                        <div class="form-group">
                                                            <div class="input-group">
                                                                <input type="text" value="{{ $student->firstName }}" class="form-control" name="firstName" required placeholder="First Name">
                                                            </div><br>
                                                            <div class="input-group">
                                                                <input type="text" value="{{ $student->lastName }}" class="form-control" name="lastName" required placeholder="Last Name">
                                                            </div><br>
                                                            <div class="input-group">
                                                                <input type="text" value="{{ $student->phone_no }}" class="form-control" name="phone_no" required placeholder="contact">
                                                            </div><br>
                                                            <div class="input-group">
                                                                <input type="email" value="{{ $student->email }}" class="form-control" name="email" required placeholder="email">
                                                            </div><br>
                                                            <div class="input-group">
                                                                <select name="gender" style="width:100%;">
                                                                    <option value="{{ $student->gender }}" selected hidden>{{ $student->gender }}</option>
                                                                    <option > Male </gender>
                                                                    <option> Female </gender>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                            <button type="submit" class="btn btn-primary">Update Details</button>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- delete Modal HTML -->
                                    <div class="modal fade" id="deleteRecord-{{ $number }}">
                                        <div class="modal-dialog modal-delete">
                                            <div class="modal-content">
                                                <div class="modal-header flex-column">
                                                    <div class="icon-box">
                                                        <i class="material-icons">clear</i>
                                                    </div>
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Do you really want to delete <strong class="text-danger"> {{  $student->firstName ." ". $student->lastName }}</strong> records? This process cannot be undone.</p>
                                                </div>
                                                <div class="modal-footer justify-content-center">
                                                    <form action="students/{{$student->id}}" method="POST">
                                                        @method('DELETE')@csrf
                                                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                                        <button type="submit" class="btn btn-danger">Delete</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </td>
                            </tr>
                            @php
                                $number++;
                            @endphp
                        @endforeach
                    @else
                        <tr>
                            <div class="text text-danger"><strong> This table have no record </strong></div>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
        <div class='pagination justify-content-center'>
            {{  $students->links()  }}
        </div>
    </div>
@endsection

@section('modal')
<!-- Add New Record Modal  -->
<div class="modal" id="addNew" tabindex="-1" role="dialog">
    <form action="{{ route('students.store') }}" method="POST">
    @csrf
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"><small>add</small> <strong>Student</strong></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="auto-form-wrapper">

                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control @error('firstName') is-invalid @enderror" name="firstName" id="firstName" placeholder="First Name">
                                @error('firstName')
                                    <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong></span>
                                @enderror
                            </div><br>
                            <div class="input-group">
                                <input type="text" class="form-control @error('lastName') is-invalid @enderror" name="lastName" id="lastName" placeholder="Last Name">
                                @error('lastName')
                                    <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong></span>
                                @enderror
                            </div><br>
                            <div class="input-group">
                                <input type="number" class="form-control @error('phone_no') is-invalid @enderror" name="phone_no" id="phone_no" placeholder="contact">
                                @error('phone_no')
                                    <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong></span>
                                @enderror
                            </div><br>
                            <div class="input-group">
                                <input type="email" class="form-control @error('email') is-invalid @enderror" name="email" id="email" placeholder="email">
                                @error('email')
                                    <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong></span>
                                @enderror
                            </div><br>
                            <div class="input-group ">
                                <select name="gender" style="width:100%;" class=" form-control @error('gender') is-invalid @enderror">
                                    <option> Male </gender>
                                    <option> Female </gender>
                                </select>
                                @error('gender')
                                    <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong></span>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </form>
</div>

@if (session('success'))
    <script type="text/javascript">
        $(document).ready(function(){
            $('#confirm').modal('show')
        })
    </script>
@elseif (session('error'))
    <script type="text/javascript">
        $(document).ready(function(){
            $('#failed').modal('show')
        })
    </script>
@endif
@endsection